"""Initial migration

Revision ID: 25a56a13dcdb
Revises: 
Create Date: 2024-12-24 19:05:41.081634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a56a13dcdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostico_presuntivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_diagnostico', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidades_medicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_especialidad', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_especialidad')
    )
    op.create_table('estudiosradiologicos',
    sa.Column('id_estudio', sa.Integer(), nullable=False),
    sa.Column('nombre_estudio', sa.String(length=100), nullable=False),
    sa.Column('descripcion_estudio', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_estudio')
    )
    op.create_table('hospitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_hospital', sa.String(length=100), nullable=False),
    sa.Column('ciudad_hospital', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicos',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('nombre_medico', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno_medico', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno_medico', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_medico')
    )
    op.create_table('operador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.Column('numero_telefonico', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('NSS', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('NSS')
    )
    op.create_table('pacientes_prueba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_estudio', sa.DateTime(), nullable=False),
    sa.Column('nss', sa.LargeBinary(), nullable=False),
    sa.Column('nombre_paciente', sa.LargeBinary(), nullable=False),
    sa.Column('apellido_paterno_paciente', sa.LargeBinary(), nullable=False),
    sa.Column('apellido_materno_paciente', sa.LargeBinary(), nullable=False),
    sa.Column('especialidad_medica', sa.LargeBinary(), nullable=False),
    sa.Column('nombre_completo_medico', sa.LargeBinary(), nullable=False),
    sa.Column('estudio_solicitado', sa.LargeBinary(), nullable=False),
    sa.Column('unidad_medica_procedencia', sa.LargeBinary(), nullable=False),
    sa.Column('diagnostico_presuntivo', sa.LargeBinary(), nullable=False),
    sa.Column('hospital_envia', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidades_medicina_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_unidad_medica', sa.String(length=100), nullable=False),
    sa.Column('direccion_unidad_medica', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena', sa.String(length=128), nullable=False),
    sa.Column('matricula', sa.BigInteger(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('nombre_real', sa.String(length=50), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('citas',
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('fecha_hora_cita', sa.DateTime(), nullable=False),
    sa.Column('nss_paciente', sa.String(length=20), nullable=False),
    sa.Column('id_medico_refiere', sa.Integer(), nullable=True),
    sa.Column('id_estudio_radiologico', sa.Integer(), nullable=True),
    sa.Column('id_usuario_registra', sa.Integer(), nullable=True),
    sa.Column('id_unidad_medica_origen', sa.Integer(), nullable=True),
    sa.Column('id_hospital_origen', sa.Integer(), nullable=True),
    sa.Column('id_operador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_estudio_radiologico'], ['estudiosradiologicos.id_estudio'], ),
    sa.ForeignKeyConstraint(['id_hospital_origen'], ['hospitales.id'], ),
    sa.ForeignKeyConstraint(['id_medico_refiere'], ['medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_operador'], ['operador.id'], ),
    sa.ForeignKeyConstraint(['id_unidad_medica_origen'], ['unidades_medicina_familiar.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_registra'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['nss_paciente'], ['pacientes.NSS'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.create_table('informes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id_cita'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informes')
    op.drop_table('citas')
    op.drop_table('usuarios')
    op.drop_table('unidades_medicina_familiar')
    op.drop_table('pacientes_prueba')
    op.drop_table('pacientes')
    op.drop_table('operador')
    op.drop_table('medicos')
    op.drop_table('hospitales')
    op.drop_table('estudiosradiologicos')
    op.drop_table('especialidades_medicas')
    op.drop_table('diagnostico_presuntivo')
    # ### end Alembic commands ###
