"""empty message

Revision ID: afd08ff897c5
Revises: 
Create Date: 2024-05-05 08:43:52.794309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd08ff897c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudios_radiologicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_estudio', sa.String(length=100), nullable=False),
    sa.Column('descripcion_estudio', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_hospital', sa.String(length=100), nullable=False),
    sa.Column('ciudad_hospital', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=50), nullable=False),
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('NSS', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('NSS')
    )
    op.create_table('unidades_medicina_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_unidad_medica', sa.String(length=100), nullable=False),
    sa.Column('direccion_unidad_medica', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('nombre_real', sa.String(length=50), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
    sa.Column('apellido_materno', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('NSS_paciente', sa.String(length=20), nullable=False),
    sa.Column('id_medico_refiere', sa.Integer(), nullable=True),
    sa.Column('id_estudio_radiologico', sa.Integer(), nullable=True),
    sa.Column('id_usuario_registra', sa.Integer(), nullable=True),
    sa.Column('id_unidad_medica_origen', sa.Integer(), nullable=True),
    sa.Column('id_hospital_origen', sa.Integer(), nullable=True),
    sa.Column('id_operador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NSS_paciente'], ['pacientes.NSS'], ),
    sa.ForeignKeyConstraint(['id_estudio_radiologico'], ['estudios_radiologicos.id'], ),
    sa.ForeignKeyConstraint(['id_hospital_origen'], ['hospitales.id'], ),
    sa.ForeignKeyConstraint(['id_medico_refiere'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['id_operador'], ['operador.id'], ),
    sa.ForeignKeyConstraint(['id_unidad_medica_origen'], ['unidades_medicina_familiar.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_registra'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cita', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Citas')
    op.drop_table('Informes')
    op.drop_table('UnidadesMedicinaFamiliar')
    op.drop_table('Medicos')
    op.drop_table('Hospitales')
    op.drop_table('Pacientes')
    op.drop_table('Usuarios')
    op.drop_table('EstudiosRadiologicos')
    with op.batch_alter_table('operador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellido_paterno', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('numero_telefonico', sa.String(length=20), nullable=True))
        batch_op.drop_column('apellido_materno_operador')
        batch_op.drop_column('nombre_operador')
        batch_op.drop_column('id_operador')
        batch_op.drop_column('numero_telefonico_operador')
        batch_op.drop_column('apellido_paterno_operador')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido_paterno_operador', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('numero_telefonico_operador', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('id_operador', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('nombre_operador', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('apellido_materno_operador', sa.TEXT(), nullable=False))
        batch_op.drop_column('numero_telefonico')
        batch_op.drop_column('apellido_materno')
        batch_op.drop_column('apellido_paterno')
        batch_op.drop_column('nombre')
        batch_op.drop_column('id')

    op.create_table('EstudiosRadiologicos',
    sa.Column('id_estudio', sa.INTEGER(), nullable=True),
    sa.Column('nombre_estudio', sa.TEXT(), nullable=False),
    sa.Column('descripcion_estudio', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_estudio')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('nombre_usuario', sa.TEXT(), nullable=False),
    sa.Column('contraseña', sa.TEXT(), nullable=False),
    sa.Column('rol', sa.TEXT(), nullable=False),
    sa.Column('nombre_real', sa.TEXT(), nullable=False),
    sa.Column('apellido_paterno', sa.TEXT(), nullable=False),
    sa.Column('apellido_materno', sa.TEXT(), nullable=False),
    sa.Column('matricula', sa.TEXT(), nullable=False),
    sa.CheckConstraint('length(matricula) <= 12'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pacientes',
    sa.Column('NSS', sa.TEXT(), nullable=True),
    sa.Column('nombre_paciente', sa.TEXT(), nullable=False),
    sa.Column('apellido_paterno_paciente', sa.TEXT(), nullable=False),
    sa.Column('apellido_materno_paciente', sa.TEXT(), nullable=False),
    sa.Column('direccion_paciente', sa.TEXT(), nullable=True),
    sa.Column('telefono_paciente', sa.TEXT(), nullable=True),
    sa.Column('sexo_paciente', sa.TEXT(), nullable=False),
    sa.Column('peso_paciente', sa.REAL(), nullable=False),
    sa.CheckConstraint("sexo_paciente IN ('M', 'F')"),
    sa.PrimaryKeyConstraint('NSS')
    )
    op.create_table('Hospitales',
    sa.Column('id_hospital', sa.INTEGER(), nullable=True),
    sa.Column('nombre_hospital', sa.TEXT(), nullable=False),
    sa.Column('ciudad_hospital', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id_hospital')
    )
    op.create_table('Medicos',
    sa.Column('id_medico', sa.INTEGER(), nullable=True),
    sa.Column('nombre_medico', sa.TEXT(), nullable=False),
    sa.Column('apellido_paterno_medico', sa.TEXT(), nullable=False),
    sa.Column('apellido_materno_medico', sa.TEXT(), nullable=False),
    sa.Column('especialidad', sa.TEXT(), nullable=False),
    sa.Column('matricula', sa.TEXT(), nullable=False),
    sa.CheckConstraint('length(matricula) <= 12'),
    sa.PrimaryKeyConstraint('id_medico')
    )
    op.create_table('UnidadesMedicinaFamiliar',
    sa.Column('id_unidad_medica', sa.INTEGER(), nullable=True),
    sa.Column('nombre_unidad_medica', sa.TEXT(), nullable=False),
    sa.Column('direccion_unidad_medica', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id_unidad_medica')
    )
    op.create_table('Informes',
    sa.Column('id_informe', sa.INTEGER(), nullable=True),
    sa.Column('id_cita_informe', sa.INTEGER(), nullable=False),
    sa.Column('contenido_informe', sa.TEXT(), nullable=True),
    sa.Column('fecha_creacion_informe', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cita_informe'], ['Citas.id_cita'], ),
    sa.PrimaryKeyConstraint('id_informe')
    )
    op.create_table('Citas',
    sa.Column('id_cita', sa.INTEGER(), nullable=True),
    sa.Column('fecha_hora_cita', sa.TEXT(), nullable=False),
    sa.Column('NSS_paciente', sa.TEXT(), nullable=False),
    sa.Column('id_medico_refiere', sa.INTEGER(), nullable=False),
    sa.Column('id_estudio_radiologico', sa.INTEGER(), nullable=False),
    sa.Column('id_usuario_registra', sa.INTEGER(), nullable=False),
    sa.Column('id_unidad_medica_origen', sa.INTEGER(), nullable=False),
    sa.Column('id_hospital_origen', sa.INTEGER(), nullable=False),
    sa.Column('diagnostico_presuntivo_cita', sa.TEXT(), nullable=True),
    sa.Column('asistencia_cita', sa.TEXT(), nullable=True),
    sa.CheckConstraint("asistencia_cita IN ('Sí', 'No')"),
    sa.ForeignKeyConstraint(['NSS_paciente'], ['Pacientes.NSS'], ),
    sa.ForeignKeyConstraint(['id_estudio_radiologico'], ['EstudiosRadiologicos.id_estudio'], ),
    sa.ForeignKeyConstraint(['id_hospital_origen'], ['Hospitales.id_hospital'], ),
    sa.ForeignKeyConstraint(['id_medico_refiere'], ['Medicos.id_medico'], ),
    sa.ForeignKeyConstraint(['id_unidad_medica_origen'], ['UnidadesMedicinaFamiliar.id_unidad_medica'], ),
    sa.ForeignKeyConstraint(['id_usuario_registra'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cita')
    )
    op.drop_table('informes')
    op.drop_table('citas')
    op.drop_table('usuarios')
    op.drop_table('unidades_medicina_familiar')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('hospitales')
    op.drop_table('estudios_radiologicos')
    # ### end Alembic commands ###
