"""empty message

Revision ID: afd08ff897c5
Revises:
Create Date: 2024-05-05 08:43:52.794309

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'afd08ff897c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('estudios_radiologicos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_estudio', sa.String(length=100), nullable=False),
        sa.Column('descripcion_estudio', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('hospitales',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_hospital', sa.String(length=100), nullable=False),
        sa.Column('ciudad_hospital', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('medicos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
        sa.Column('apellido_materno', sa.String(length=50), nullable=False),
        sa.Column('especialidad', sa.String(length=50), nullable=False),
        sa.Column('matricula', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('pacientes',
        sa.Column('NSS', sa.String(length=20), nullable=False),
        sa.Column('nombre', sa.String(length=50), nullable=False),
        sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
        sa.Column('apellido_materno', sa.String(length=50), nullable=False),
        sa.Column('direccion', sa.String(length=100), nullable=True),
        sa.Column('telefono', sa.String(length=20), nullable=True),
        sa.Column('sexo', sa.String(length=1), nullable=False),
        sa.Column('peso', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('NSS')
    )

    op.create_table('unidades_medicina_familiar',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_unidad_medica', sa.String(length=100), nullable=False),
        sa.Column('direccion_unidad_medica', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
        sa.Column('contraseña', sa.String(length=128), nullable=False),
        sa.Column('rol', sa.String(length=50), nullable=False),
        sa.Column('nombre_real', sa.String(length=50), nullable=False),
        sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
        sa.Column('apellido_materno', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # 1) CREA la tabla 'operador' antes de 'citas'
    op.create_table('operador',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('apellido_paterno', sa.String(length=50), nullable=False),
        sa.Column('apellido_materno', sa.String(length=50), nullable=False),
        sa.Column('numero_telefonico', sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # 2) Ahora sí, crea la tabla 'citas' con la foreign key a 'operador.id'
    op.create_table('citas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fecha_hora', sa.DateTime(), nullable=False),
        sa.Column('NSS_paciente', sa.String(length=20), nullable=False),
        sa.Column('id_medico_refiere', sa.Integer(), nullable=True),
        sa.Column('id_estudio_radiologico', sa.Integer(), nullable=True),
        sa.Column('id_usuario_registra', sa.Integer(), nullable=True),
        sa.Column('id_unidad_medica_origen', sa.Integer(), nullable=True),
        sa.Column('id_hospital_origen', sa.Integer(), nullable=True),
        sa.Column('id_operador', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['NSS_paciente'], ['pacientes.NSS'], ),
        sa.ForeignKeyConstraint(['id_estudio_radiologico'], ['estudios_radiologicos.id'], ),
        sa.ForeignKeyConstraint(['id_hospital_origen'], ['hospitales.id'], ),
        sa.ForeignKeyConstraint(['id_medico_refiere'], ['medicos.id'], ),
        sa.ForeignKeyConstraint(['id_operador'], ['operador.id'], ),  # <--- ya existe 'operador'
        sa.ForeignKeyConstraint(['id_unidad_medica_origen'], ['unidades_medicina_familiar.id'], ),
        sa.ForeignKeyConstraint(['id_usuario_registra'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('informes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_cita', sa.Integer(), nullable=False),
        sa.Column('contenido', sa.Text(), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['id_cita'], ['citas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informes')
    op.drop_table('citas')
    op.drop_table('operador')
    op.drop_table('usuarios')
    op.drop_table('unidades_medicina_familiar')
    op.drop_table('pacientes')
    op.drop_table('medicos')
    op.drop_table('hospitales')
    op.drop_table('estudios_radiologicos')
    # ### end Alembic commands ###
