name: SonarCloud
on:
  push:
    branches:
      - main
      - test-build
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install JavaScript dependencies
        run: npm install

      - name: Run tests
        run: |
          npm test || true
          pytest || true

      - name: Run SonarCloud analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=SWGCM1.2 \
            -Dsonar.organization=benohe3018 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=. \
            -Dsonar.exclusions=**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/** \
            -Dsonar.tests=. \
            -Dsonar.test.inclusions=**/tests/**,**/test/**,**/*.spec.js,**/*.spec.jsx,**/*.test.js,**/*.test.jsx \
            -Dsonar.test.exclusions=**/__pycache__/**,**/node_modules/**,**/dist/**,**/build/** \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.python.xunit.reportPath=reports/xunit.xml \
            -Dsonar.python.coverage.reportPaths=reports/coverage.xml

